#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: JupyterLab Lite
# Runs the Nginx daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

# Wait for JupyterLab to become available
s6-svwait -u -t 5000 /var/run/s6/services/jupyter

exec nginx -g "daemon off;"
