#!/usr/bin/with-contenv bash
# shellcheck disable=SC2191
# ==============================================================================
# Community Hass.io Add-ons: JupyterLab Lite
# Runs Jupyter
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

hass.log.info 'Starting the Jupyter server'

# Find the matching Jupyter log level
case "$(hass.string.lower "$(hass.config.get 'log_level')")" in
    all|trace|debug)
        options+=(--log-level='DEBUG')
        ;;
    info|notice)
        options+=(--log-level='INFO')
        ;;
    warning)
        options+=(--log-level='WARN')
        ;;
    error)
        options+=(--log-level='ERROR')
        ;;
    fatal|off)
        options+=(--log-level='CRITICAL')
        ;;
esac

# SSL Configuration
if hass.config.true 'ssl'; then
    options+=(--keyfile="/ssl/$(hass.config.get 'keyfile')")
    options+=(--certfile="/ssl/$(hass.config.get 'certfile')")
fi

# Change current working directory
cd /config/notebooks || hass.die 'Failed changing working directory'

# Run Juypter Notebook server
exec jupyter lab "${options[@]}"
